import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  buildEvidenceManifest,
  parseEvidenceManifest,
  type EvidenceEvent,
  type ReviewEvidenceInput,
} from "../src/evidence-manifest.ts";

const review: ReviewEvidenceInput = {
  kind: "review",
  guardPublicKeyPrefix: "ab12",
  origin: "external",
  scheduleId: "0.0.7001",
  outcome: "approved",
  decidingInvariant: "recipient is on the mandate allowlist",
  mandateDigest: "a".repeat(64),
  mandatePolicy: {
    asset: { kind: "hbar" },
    recipientAllowlist: ["0.0.1002"],
    maxAmountTinybars: "50000000",
    validFromEpochSeconds: "1788508800",
    expiresAtEpochSeconds: "1788512400",
  },
  settlementId: "0.0.7162784@1788509000.000000001",
  settlementAmountTinybars: "1000000",
  paymentPayerAccountId: "0.0.8001",
};

test("INVARIANT: a record without an explicit origin must be refused", () => {
  const { origin: _origin, ...withoutOrigin } = review;

  assert.throws(
    () => buildEvidenceManifest([withoutOrigin as unknown as EvidenceEvent]),
    /origin must be operator or external/,
  );
});

test("INVARIANT: operator and external counts must never be summed into one field", () => {
  const manifest = buildEvidenceManifest([
    review,
    { ...review, scheduleId: "0.0.7002", outcome: "refused" },
    {
      ...review,
      origin: "operator",
      scheduleId: "0.0.7003",
      paymentPayerAccountId: "0.0.8002",
    },
  ]);

  assert.deepEqual(manifest.counts, {
    external: {
      reviewCount: 2,
      approvalCount: 1,
      refusalCount: 1,
      distinctPayerAccountCount: 1,
    },
    operator: {
      reviewCount: 1,
      approvalCount: 1,
      refusalCount: 0,
    },
  });
  assert.equal("total" in manifest.counts, false);
  assert.equal("reviewCount" in manifest.counts, false);
  assert.equal("approvalCount" in manifest.counts, false);
  assert.equal("refusalCount" in manifest.counts, false);
});

test("a setup transaction is not counted as a review", () => {
  const manifest = buildEvidenceManifest([
    {
      kind: "setup",
      origin: "operator",
      transactionId: "0.0.8001@1788508000.000000001",
      purpose: "account creation",
    },
  ]);

  assert.equal(manifest.records.length, 0);
  assert.equal(manifest.setupTransactions.length, 1);
  assert.equal(manifest.counts.external.reviewCount, 0);
  assert.equal(manifest.counts.operator.reviewCount, 0);
});

test("the empty manifest validates and exposes only separated zero counts", () => {
  const manifest = buildEvidenceManifest([]);

  assert.deepEqual(parseEvidenceManifest(manifest), manifest);
  assert.deepEqual(manifest.counts, {
    external: {
      reviewCount: 0,
      approvalCount: 0,
      refusalCount: 0,
      distinctPayerAccountCount: 0,
    },
    operator: {
      reviewCount: 0,
      approvalCount: 0,
      refusalCount: 0,
    },
  });
});

test("manifest validation rejects a non-string guard public-key prefix", () => {
  const manifest = buildEvidenceManifest([review]);

  assert.throws(
    () =>
      parseEvidenceManifest({
        ...manifest,
        records: [{ ...manifest.records[0], guardPublicKeyPrefix: 12 }],
      }),
    /guardPublicKeyPrefix must be a non-empty string/,
  );
});

test("manifest validation does not depend on count-field property order", () => {
  const manifest = buildEvidenceManifest([]);

  assert.deepEqual(
    parseEvidenceManifest({
      ...manifest,
      counts: {
        operator: {
          refusalCount: 0,
          approvalCount: 0,
          reviewCount: 0,
        },
        external: {
          distinctPayerAccountCount: 0,
          refusalCount: 0,
          approvalCount: 0,
          reviewCount: 0,
        },
      },
    }),
    manifest,
  );
});

test("the produced JSON satisfies the evidence page contract", async () => {
  const pageSource = await readFile(
    new URL("../web/evidence.html", import.meta.url),
    "utf8",
  );
  const raw = await readFile(
    new URL("../web/evidence.json", import.meta.url),
    "utf8",
  );
  const checkedIn = parseEvidenceManifest(JSON.parse(raw));

  // The manifest is generated by scripts/build-evidence.ts from the recorded runs.
  // Byte identity after a parse and re-serialise proves it was never hand-edited,
  // so its counts cannot overstate what actually happened on chain.
  assert.equal(`${JSON.stringify(checkedIn, null, 2)}
`, raw);
  assert.match(pageSource, /data\.records/);
  assert.match(pageSource, /record\.guardPublicKeyPrefix/);
  assert.match(pageSource, /No reviews recorded yet\./);
});

test("review records carry canonical schedule and payer mirror links", () => {
  const [record] = buildEvidenceManifest([review]).records;

  assert.equal(
    record?.mirrorNodeUrl,
    "https://testnet.mirrornode.hedera.com/api/v1/schedules/0.0.7001",
  );
  assert.equal(
    record?.paymentPayerMirrorNodeUrl,
    "https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.8001",
  );
});

test("INVARIANT: combined reviews must preserve each record's guard identity", () => {
  const events = [
    { ...review, guardPublicKeyPrefix: "ab12" },
    { ...review, scheduleId: "0.0.7002", guardPublicKeyPrefix: "cd34" },
  ];
  const manifest = buildEvidenceManifest(events);
  assert.deepEqual(
    manifest.records.map((record) => record.guardPublicKeyPrefix),
    ["ab12", "cd34"],
  );
  assert.deepEqual(parseEvidenceManifest(manifest), manifest);
  assert.equal("guardPublicKeyPrefix" in manifest, false);
});

for (const guardPublicKeyPrefix of ["", "abc", "not-hex", 12]) {
  test(`INVARIANT: review guard identity ${String(guardPublicKeyPrefix)} must be refused`, () => {
    assert.throws(
      () => buildEvidenceManifest([
        { ...review, guardPublicKeyPrefix } as unknown as ReviewEvidenceInput,
      ]),
      /guardPublicKeyPrefix must be/,
    );
  });
}

test("INVARIANT: a review without a guard identity cannot be interpreted using a global identity", () => {
  const { guardPublicKeyPrefix, ...withoutGuard } = review;
  assert.equal(guardPublicKeyPrefix, "ab12");
  assert.throws(
    () => buildEvidenceManifest([withoutGuard as ReviewEvidenceInput]),
    /missing review record field: guardPublicKeyPrefix/,
  );
});
