HBAR_ASSET_ID = "0.0.0"
HEDERA_MAINNET_CAIP2 = "hedera:mainnet"
HEDERA_TESTNET_CAIP2 = "hedera:testnet"
SUPPORTED_HEDERA_NETWORKS = frozenset(
    {HEDERA_MAINNET_CAIP2, HEDERA_TESTNET_CAIP2}
)
DEFAULT_NODE_ACCOUNT_ID = "0.0.3"
